import type {
    CurrencyRate,
    LoanInput,
    TaxBracket,
    UnitCategory,
    UnitDefinition,
    UnitConversionInput,
    YearEndBonusTaxInput
} from '@/types/calculator'

export const CALCULATOR_POLICY_VERSION = '2023-08-18 年终奖个税政策延续公告'

export const YEAR_END_BONUS_POLICY_VALID_UNTIL = '2027-12-31'

export const ANNUAL_TAX_BRACKETS: TaxBracket[] = [
    {upper: 36000, rate: 0.03, quickDeduction: 0},
    {upper: 144000, rate: 0.1, quickDeduction: 2520},
    {upper: 300000, rate: 0.2, quickDeduction: 16920},
    {upper: 420000, rate: 0.25, quickDeduction: 31920},
    {upper: 660000, rate: 0.3, quickDeduction: 52920},
    {upper: 960000, rate: 0.35, quickDeduction: 85920},
    {upper: null, rate: 0.45, quickDeduction: 181920}
]

export const MONTHLY_TAX_BRACKETS: TaxBracket[] = [
    {upper: 3000, rate: 0.03, quickDeduction: 0},
    {upper: 12000, rate: 0.1, quickDeduction: 210},
    {upper: 25000, rate: 0.2, quickDeduction: 1410},
    {upper: 35000, rate: 0.25, quickDeduction: 2660},
    {upper: 55000, rate: 0.3, quickDeduction: 4410},
    {upper: 80000, rate: 0.35, quickDeduction: 7160},
    {upper: null, rate: 0.45, quickDeduction: 15160}
]

export const UNIT_CATEGORIES: Array<{value: UnitCategory; label: string}> = [
    {value: 'length', label: '长度'},
    {value: 'weight', label: '重量'},
    {value: 'area', label: '面积'},
    {value: 'volume', label: '体积'},
    {value: 'temperature', label: '温度'},
    {value: 'data', label: '数据容量'}
]

export const UNIT_DEFINITIONS: UnitDefinition[] = [
    {category: 'length', value: 'mm', label: '毫米', symbol: 'mm', factorToBase: 0.001},
    {category: 'length', value: 'cm', label: '厘米', symbol: 'cm', factorToBase: 0.01},
    {category: 'length', value: 'm', label: '米', symbol: 'm', factorToBase: 1},
    {category: 'length', value: 'km', label: '千米', symbol: 'km', factorToBase: 1000},
    {category: 'length', value: 'in', label: '英寸', symbol: 'in', factorToBase: 0.0254},
    {category: 'length', value: 'ft', label: '英尺', symbol: 'ft', factorToBase: 0.3048},
    {category: 'length', value: 'yd', label: '码', symbol: 'yd', factorToBase: 0.9144},
    {category: 'length', value: 'mi', label: '英里', symbol: 'mi', factorToBase: 1609.344},

    {category: 'weight', value: 'mg', label: '毫克', symbol: 'mg', factorToBase: 0.000001},
    {category: 'weight', value: 'g', label: '克', symbol: 'g', factorToBase: 0.001},
    {category: 'weight', value: 'kg', label: '千克', symbol: 'kg', factorToBase: 1},
    {category: 'weight', value: 't', label: '吨', symbol: 't', factorToBase: 1000},
    {category: 'weight', value: 'jin', label: '斤', symbol: '斤', factorToBase: 0.5},
    {category: 'weight', value: 'oz', label: '盎司', symbol: 'oz', factorToBase: 0.028349523125},
    {category: 'weight', value: 'lb', label: '磅', symbol: 'lb', factorToBase: 0.45359237},

    {category: 'area', value: 'cm2', label: '平方厘米', symbol: 'cm²', factorToBase: 0.0001},
    {category: 'area', value: 'm2', label: '平方米', symbol: 'm²', factorToBase: 1},
    {category: 'area', value: 'km2', label: '平方千米', symbol: 'km²', factorToBase: 1000000},
    {category: 'area', value: 'mu', label: '亩', symbol: '亩', factorToBase: 666.6666666667},
    {category: 'area', value: 'ha', label: '公顷', symbol: 'ha', factorToBase: 10000},
    {category: 'area', value: 'ft2', label: '平方英尺', symbol: 'ft²', factorToBase: 0.09290304},
    {category: 'area', value: 'acre', label: '英亩', symbol: 'acre', factorToBase: 4046.8564224},

    {category: 'volume', value: 'ml', label: '毫升', symbol: 'ml', factorToBase: 0.001},
    {category: 'volume', value: 'l', label: '升', symbol: 'L', factorToBase: 1},
    {category: 'volume', value: 'm3', label: '立方米', symbol: 'm³', factorToBase: 1000},
    {category: 'volume', value: 'cup', label: '杯', symbol: 'cup', factorToBase: 0.24},
    {category: 'volume', value: 'gal-us', label: '美制加仑', symbol: 'gal', factorToBase: 3.785411784},

    {category: 'temperature', value: 'c', label: '摄氏度', symbol: '°C'},
    {category: 'temperature', value: 'f', label: '华氏度', symbol: '°F'},
    {category: 'temperature', value: 'k', label: '开尔文', symbol: 'K'},

    {category: 'data', value: 'bit', label: '比特', symbol: 'bit', factorToBase: 0.125},
    {category: 'data', value: 'b', label: '字节', symbol: 'B', factorToBase: 1},
    {category: 'data', value: 'kb', label: 'KB', symbol: 'KB', factorToBase: 1024},
    {category: 'data', value: 'mb', label: 'MB', symbol: 'MB', factorToBase: 1024 ** 2},
    {category: 'data', value: 'gb', label: 'GB', symbol: 'GB', factorToBase: 1024 ** 3},
    {category: 'data', value: 'tb', label: 'TB', symbol: 'TB', factorToBase: 1024 ** 4}
]

// 手动模式默认值仅作为初始参考；实时模式以后端汇率接口返回为准。
export const DEFAULT_CURRENCY_RATES: CurrencyRate[] = [
    {code: 'CNY', label: '人民币', rateToCny: 1},
    {code: 'USD', label: '美元', rateToCny: 7.2},
    {code: 'JPY', label: '日元', rateToCny: 0.05},
    {code: 'KRW', label: '韩元', rateToCny: 0.0052},
    {code: 'EUR', label: '欧元', rateToCny: 7.8},
    {code: 'HKD', label: '港币', rateToCny: 0.92},
    {code: 'AUD', label: '澳元', rateToCny: 4.75},
    {code: 'GBP', label: '英镑', rateToCny: 9.1},
    {code: 'AED', label: '阿联酋迪拉姆', rateToCny: 1.96},
    {code: 'AFN', label: '阿富汗尼', rateToCny: 0.1},
    {code: 'ALL', label: '阿尔巴尼亚列克', rateToCny: 0.08},
    {code: 'AMD', label: '亚美尼亚德拉姆', rateToCny: 0.018},
    {code: 'ANG', label: '荷属安的列斯盾', rateToCny: 4.02},
    {code: 'AOA', label: '安哥拉宽扎', rateToCny: 0.0079},
    {code: 'ARS', label: '阿根廷比索', rateToCny: 0.0058},
    {code: 'AWG', label: '阿鲁巴弗罗林', rateToCny: 4},
    {code: 'AZN', label: '阿塞拜疆马纳特', rateToCny: 4.24},
    {code: 'BAM', label: '波黑可兑换马克', rateToCny: 3.99},
    {code: 'BBD', label: '巴巴多斯元', rateToCny: 3.6},
    {code: 'BDT', label: '孟加拉塔卡', rateToCny: 0.059},
    {code: 'BGN', label: '保加利亚列弗', rateToCny: 3.99},
    {code: 'BHD', label: '巴林第纳尔', rateToCny: 19.1},
    {code: 'BIF', label: '布隆迪法郎', rateToCny: 0.0025},
    {code: 'BMD', label: '百慕大元', rateToCny: 7.2},
    {code: 'BND', label: '文莱元', rateToCny: 5.4},
    {code: 'BOB', label: '玻利维亚诺', rateToCny: 1.04},
    {code: 'BRL', label: '巴西雷亚尔', rateToCny: 1.32},
    {code: 'BSD', label: '巴哈马元', rateToCny: 7.2},
    {code: 'BTN', label: '不丹努尔特鲁姆', rateToCny: 0.084},
    {code: 'BWP', label: '博茨瓦纳普拉', rateToCny: 0.52},
    {code: 'BYN', label: '白俄罗斯卢布', rateToCny: 2.2},
    {code: 'BZD', label: '伯利兹元', rateToCny: 3.58},
    {code: 'CAD', label: '加拿大元', rateToCny: 5.27},
    {code: 'CDF', label: '刚果法郎', rateToCny: 0.0025},
    {code: 'CHF', label: '瑞士法郎', rateToCny: 8.2},
    {code: 'CLP', label: '智利比索', rateToCny: 0.0077},
    {code: 'CNH', label: '离岸人民币', rateToCny: 1},
    {code: 'COP', label: '哥伦比亚比索', rateToCny: 0.0018},
    {code: 'CRC', label: '哥斯达黎加科朗', rateToCny: 0.014},
    {code: 'CUP', label: '古巴比索', rateToCny: 0.3},
    {code: 'CVE', label: '佛得角埃斯库多', rateToCny: 0.071},
    {code: 'CZK', label: '捷克克朗', rateToCny: 0.32},
    {code: 'DJF', label: '吉布提法郎', rateToCny: 0.04},
    {code: 'DKK', label: '丹麦克朗', rateToCny: 1.04},
    {code: 'DOP', label: '多米尼加比索', rateToCny: 0.12},
    {code: 'DZD', label: '阿尔及利亚第纳尔', rateToCny: 0.053},
    {code: 'EGP', label: '埃及镑', rateToCny: 0.15},
    {code: 'ERN', label: '厄立特里亚纳克法', rateToCny: 0.48},
    {code: 'ETB', label: '埃塞俄比亚比尔', rateToCny: 0.052},
    {code: 'FJD', label: '斐济元', rateToCny: 3.2},
    {code: 'FKP', label: '福克兰群岛镑', rateToCny: 9.1},
    {code: 'GEL', label: '格鲁吉亚拉里', rateToCny: 2.66},
    {code: 'GHS', label: '加纳塞地', rateToCny: 0.48},
    {code: 'GIP', label: '直布罗陀镑', rateToCny: 9.1},
    {code: 'GMD', label: '冈比亚达拉西', rateToCny: 0.1},
    {code: 'GNF', label: '几内亚法郎', rateToCny: 0.00084},
    {code: 'GTQ', label: '危地马拉格查尔', rateToCny: 0.93},
    {code: 'GYD', label: '圭亚那元', rateToCny: 0.034},
    {code: 'HNL', label: '洪都拉斯伦皮拉', rateToCny: 0.28},
    {code: 'HTG', label: '海地古德', rateToCny: 0.055},
    {code: 'HUF', label: '匈牙利福林', rateToCny: 0.019},
    {code: 'IDR', label: '印尼盾', rateToCny: 0.00044},
    {code: 'ILS', label: '以色列新谢克尔', rateToCny: 2.1},
    {code: 'INR', label: '印度卢比', rateToCny: 0.084},
    {code: 'IQD', label: '伊拉克第纳尔', rateToCny: 0.0055},
    {code: 'IRR', label: '伊朗里亚尔', rateToCny: 0.00017},
    {code: 'ISK', label: '冰岛克朗', rateToCny: 0.058},
    {code: 'JMD', label: '牙买加元', rateToCny: 0.046},
    {code: 'JOD', label: '约旦第纳尔', rateToCny: 10.15},
    {code: 'KES', label: '肯尼亚先令', rateToCny: 0.056},
    {code: 'KGS', label: '吉尔吉斯斯坦索姆', rateToCny: 0.083},
    {code: 'KHR', label: '柬埔寨瑞尔', rateToCny: 0.0018},
    {code: 'KMF', label: '科摩罗法郎', rateToCny: 0.016},
    {code: 'KPW', label: '朝鲜圆', rateToCny: 0.008},
    {code: 'KWD', label: '科威特第纳尔', rateToCny: 23.5},
    {code: 'KYD', label: '开曼群岛元', rateToCny: 8.65},
    {code: 'KZT', label: '哈萨克斯坦坚戈', rateToCny: 0.014},
    {code: 'LAK', label: '老挝基普', rateToCny: 0.00033},
    {code: 'LBP', label: '黎巴嫩镑', rateToCny: 0.00008},
    {code: 'LKR', label: '斯里兰卡卢比', rateToCny: 0.024},
    {code: 'LRD', label: '利比里亚元', rateToCny: 0.036},
    {code: 'LSL', label: '莱索托洛蒂', rateToCny: 0.4},
    {code: 'LYD', label: '利比亚第纳尔', rateToCny: 1.5},
    {code: 'MAD', label: '摩洛哥迪拉姆', rateToCny: 0.72},
    {code: 'MDL', label: '摩尔多瓦列伊', rateToCny: 0.4},
    {code: 'MGA', label: '马达加斯加阿里亚里', rateToCny: 0.0016},
    {code: 'MKD', label: '北马其顿代纳尔', rateToCny: 0.127},
    {code: 'MMK', label: '缅甸元', rateToCny: 0.0034},
    {code: 'MNT', label: '蒙古图格里克', rateToCny: 0.0021},
    {code: 'MOP', label: '澳门元', rateToCny: 0.9},
    {code: 'MRU', label: '毛里塔尼亚乌吉亚', rateToCny: 0.18},
    {code: 'MUR', label: '毛里求斯卢比', rateToCny: 0.16},
    {code: 'MVR', label: '马尔代夫拉菲亚', rateToCny: 0.47},
    {code: 'MWK', label: '马拉维克瓦查', rateToCny: 0.0042},
    {code: 'MXN', label: '墨西哥比索', rateToCny: 0.39},
    {code: 'MYR', label: '马来西亚林吉特', rateToCny: 1.53},
    {code: 'MZN', label: '莫桑比克梅蒂卡尔', rateToCny: 0.113},
    {code: 'NAD', label: '纳米比亚元', rateToCny: 0.4},
    {code: 'NGN', label: '尼日利亚奈拉', rateToCny: 0.0046},
    {code: 'NIO', label: '尼加拉瓜科多巴', rateToCny: 0.196},
    {code: 'NOK', label: '挪威克朗', rateToCny: 0.68},
    {code: 'NPR', label: '尼泊尔卢比', rateToCny: 0.052},
    {code: 'NZD', label: '新西兰元', rateToCny: 4.3},
    {code: 'OMR', label: '阿曼里亚尔', rateToCny: 18.7},
    {code: 'PAB', label: '巴拿马巴波亚', rateToCny: 7.2},
    {code: 'PEN', label: '秘鲁索尔', rateToCny: 1.95},
    {code: 'PGK', label: '巴布亚新几内亚基那', rateToCny: 1.8},
    {code: 'PHP', label: '菲律宾比索', rateToCny: 0.127},
    {code: 'PKR', label: '巴基斯坦卢比', rateToCny: 0.026},
    {code: 'PLN', label: '波兰兹罗提', rateToCny: 1.84},
    {code: 'PYG', label: '巴拉圭瓜拉尼', rateToCny: 0.00093},
    {code: 'QAR', label: '卡塔尔里亚尔', rateToCny: 1.98},
    {code: 'RON', label: '罗马尼亚列伊', rateToCny: 1.57},
    {code: 'RSD', label: '塞尔维亚第纳尔', rateToCny: 0.067},
    {code: 'RUB', label: '俄罗斯卢布', rateToCny: 0.09},
    {code: 'RWF', label: '卢旺达法郎', rateToCny: 0.005},
    {code: 'SAR', label: '沙特里亚尔', rateToCny: 1.92},
    {code: 'SBD', label: '所罗门群岛元', rateToCny: 0.86},
    {code: 'SCR', label: '塞舌尔卢比', rateToCny: 0.53},
    {code: 'SDG', label: '苏丹镑', rateToCny: 0.012},
    {code: 'SEK', label: '瑞典克朗', rateToCny: 0.73},
    {code: 'SGD', label: '新加坡元', rateToCny: 5.4},
    {code: 'SHP', label: '圣赫勒拿镑', rateToCny: 9.1},
    {code: 'SLE', label: '塞拉利昂利昂', rateToCny: 0.32},
    {code: 'SOS', label: '索马里先令', rateToCny: 0.0126},
    {code: 'SRD', label: '苏里南元', rateToCny: 0.2},
    {code: 'SSP', label: '南苏丹镑', rateToCny: 0.0055},
    {code: 'STN', label: '圣多美和普林西比多布拉', rateToCny: 0.32},
    {code: 'SYP', label: '叙利亚镑', rateToCny: 0.00055},
    {code: 'SZL', label: '斯威士兰里兰吉尼', rateToCny: 0.4},
    {code: 'THB', label: '泰铢', rateToCny: 0.22},
    {code: 'TJS', label: '塔吉克斯坦索莫尼', rateToCny: 0.68},
    {code: 'TMT', label: '土库曼斯坦马纳特', rateToCny: 2.06},
    {code: 'TND', label: '突尼斯第纳尔', rateToCny: 2.35},
    {code: 'TOP', label: '汤加潘加', rateToCny: 3.05},
    {code: 'TRY', label: '土耳其里拉', rateToCny: 0.18},
    {code: 'TTD', label: '特立尼达和多巴哥元', rateToCny: 1.06},
    {code: 'TWD', label: '新台币', rateToCny: 0.22},
    {code: 'TZS', label: '坦桑尼亚先令', rateToCny: 0.0028},
    {code: 'UAH', label: '乌克兰格里夫纳', rateToCny: 0.17},
    {code: 'UGX', label: '乌干达先令', rateToCny: 0.0019},
    {code: 'UYU', label: '乌拉圭比索', rateToCny: 0.18},
    {code: 'UZS', label: '乌兹别克斯坦苏姆', rateToCny: 0.00056},
    {code: 'VED', label: '委内瑞拉数字玻利瓦尔', rateToCny: 0.07},
    {code: 'VES', label: '委内瑞拉玻利瓦尔', rateToCny: 0.07},
    {code: 'VND', label: '越南盾', rateToCny: 0.00028},
    {code: 'VUV', label: '瓦努阿图瓦图', rateToCny: 0.061},
    {code: 'WST', label: '萨摩亚塔拉', rateToCny: 2.6},
    {code: 'XAF', label: '中非法郎', rateToCny: 0.0119},
    {code: 'XCD', label: '东加勒比元', rateToCny: 2.66},
    {code: 'XCG', label: '加勒比荷兰盾', rateToCny: 4},
    {code: 'XOF', label: '西非法郎', rateToCny: 0.0119},
    {code: 'XPF', label: '太平洋法郎', rateToCny: 0.065},
    {code: 'YER', label: '也门里亚尔', rateToCny: 0.03},
    {code: 'ZAR', label: '南非兰特', rateToCny: 0.4},
    {code: 'ZMW', label: '赞比亚克瓦查', rateToCny: 0.27},
    {code: 'ZWL', label: '津巴布韦元', rateToCny: 0.022}
]

export const createDefaultLoanInput = (): LoanInput => ({
    kind: 'mortgage',
    totalPrice: 2000000,
    downPayment: 600000,
    principal: 1400000,
    annualRate: 3.45,
    months: 360,
    method: 'equal-payment',
    serviceFee: 0
})

export const createDefaultYearEndBonusTaxInput = (): YearEndBonusTaxInput => ({
    bonus: 60000,
    annualIncomeWithoutBonus: 180000,
    basicDeduction: 60000,
    specialDeductions: 36000,
    specialAdditionalDeductions: 24000,
    otherDeductions: 0,
    prepaidTaxWithoutBonus: 0
})

export const createDefaultUnitInput = (): UnitConversionInput => ({
    category: 'length',
    amount: 1,
    fromUnit: 'm',
    toUnit: 'cm',
    precision: 4
})
